# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
# ---------------------------------------------------------------------------
# Orderer
# ---------------------------------------------------------------------------
  - Name: org0
    Domain: org0
    CA:
      Country: KR
      Province: Gyunggi
      Locality: Seongnam
      OrganizationalUnit: skcc0
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
        CommonName: orderer1
      - Hostname: orderer2
        CommonName: orderer2
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: org1
    Domain: org1
    EnableNodeOUs: true
    CA:
      Country: KR
      Province: Gyunggi
      Locality: Seongnam
      OrganizationalUnit: skcc1
    Specs:
      - Hostname: peer1
        CommonName: peer1
      - Hostname: peer2
        CommonName: peer2
    Users:
      Count: 1
# ---------------------------------------------------------------------------
# Org2: See "Org1" for full specification
# ---------------------------------------------------------------------------
  - Name: org2
    Domain: org2
    EnableNodeOUs: true
    CA:
      Country: KR
      Province: Gyunggi
      Locality: Seongnam
      OrganizationalUnit: skcc2
    Specs:
      - Hostname: peer5
        CommonName: peer5
      - Hostname: peer6
        CommonName: peer6
    Users:
      Count: 1

